name: rumor
channels:
  - conda-forge
dependencies:
  - adjusttext=1.0.4
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - ipython=8.21.0
  - jupyter=1.0.0
  - matplotlib=3.8.3
  - nltk=3.8.1
  - numpy=1.26.4
  - openssl=3.2.1
  - pandas=2.2.0
  - python=3.11.8
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - seaborn=0.13.2
  - sentence-transformers=2.3.1
  - statsmodels=0.14.1
  - umap-learn=0.5.5
